---
- name: Ensure we are using apk
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apk as a package manager."
  when: ansible_pkg_mgr != "apk"

- name: Remove common packages via apk
  block:
    - name: Ensure common apk packages are removed
      community.general.apk:
        name: "{{ package }}"
        state: absent
      loop: "{{ common_pkgs.apk.remove }}"
      loop_control:
        loop_var: package
      become: true

    - name: Remove common apk packages matching regex
      block:
        - name: Get list of installed apk packages matching each regex
          ansible.builtin.shell: |
            set -o pipefail
            apk list --installed | awk -F' ' '{print $1}' | grep -E -- '{{ regex }}'
          loop: "{{ common_pkgs.apk.remove_regex }}"
          loop_control:
            loop_var: regex
          register: common_pkgs_apk_remove_regex_result
          args:
            executable: /bin/sh
          when: common_pkgs.apk.remove_regex | length > 0
          changed_when: false
          failed_when: false

        - name: Ensure common apk packages matching regex are removed
          community.general.apk:
            name: "{{ package }}"
            state: absent
          loop: "{{ common_pkgs_apk_remove_regex_result.results | map(attribute='stdout_lines') | flatten | unique }}"
          loop_control:
            loop_var: package
          when:
            - common_pkgs_apk_remove_regex_result is defined
            - common_pkgs_apk_remove_regex_result.results | length > 0
          become: true
