---
- name: Ensure we are using apt
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apt as a package manager."
  when: ansible_pkg_mgr != "apt"

- name: Remove common packages via apt
  block:
    - name: Ensure common apt packages are removed
      ansible.builtin.apt:
        name: "{{ package }}"
        purge: "{{ common_pkgs.apt.remove_modified_configs }}"
        state: absent
      loop: "{{ common_pkgs.apt.remove }}"
      loop_control:
        loop_var: package
      become: true

    - name: Remove common apt packages matching regex
      block:
        - name: Get list of installed apt packages matching each regex
          ansible.builtin.shell: |
            set -o pipefail
            dpkg-query -W -f='${Package}\n' | grep -E -- '{{ regex }}'
          loop: "{{ common_pkgs.apt.remove_regex }}"
          loop_control:
            loop_var: regex
          register: common_pkgs_apt_remove_regex_result
          args:
            executable: /bin/bash
          when: common_pkgs.apt.remove_regex | length > 0
          changed_when: false
          failed_when: false # Handle if no packages match the regex

        - name: Ensure common apt packages matching regex are removed
          ansible.builtin.apt:
            name: "{{ package }}"
            purge: "{{ common_pkgs.apt.remove_modified_configs }}"
            state: absent
          loop: "{{ common_pkgs_apt_remove_regex_result.results | map(attribute='stdout_lines') | flatten | unique }}"
          loop_control:
            loop_var: package
          when:
            - common_pkgs_apt_remove_regex_result is defined
            - common_pkgs_apt_remove_regex_result.results | length > 0
          become: true

    - name: Perform cleanup
      block:
        - name: Remove useless packages from the cache
          ansible.builtin.apt:
            autoclean: true
          become: true

        - name: Remove dependencies that are no longer required
          ansible.builtin.apt:
            autoremove: true
            purge: "{{ common_pkgs.apt.remove_modified_configs }}"
          become: true
