---
- name: Prepare
  hosts: all
  gather_facts: true

  vars_files:
    - ../../vars/molecule.yml

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Debian preparation
      when: ansible_os_family == 'Debian'
      block:
        - name: Install packages that will be removed by the role (direct)
          ansible.builtin.package:
            name: "{{ common_pkgs_apt.remove }}"
            state: present
          become: true

        - name: Install packages that will be removed by the role (regex targets)
          ansible.builtin.package:
            name: "{{ common_pkgs_apt.remove_regex_test }}"
            state: present
          become: true
          when: common_pkgs_apt.remove_regex_test is defined

    - name: Archlinux preparation
      when: ansible_os_family == 'Archlinux'
      block:
        - name: Install packages that will be removed by the role (direct)
          ansible.builtin.package:
            name: "{{ common_pkgs_pacman.remove }}"
            state: present
          become: true

        - name: Install packages that will be removed by the role (regex targets)
          ansible.builtin.package:
            name: "{{ common_pkgs_pacman.remove_regex_test }}"
            state: present
          become: true
          when: common_pkgs_pacman.remove_regex_test is defined

    - name: Alpine preparation
      when: ansible_os_family == 'Alpine'
      block:
        - name: Install packages that will be removed by the role (direct)
          ansible.builtin.package:
            name: "{{ common_pkgs_apk.remove }}"
            state: present
          become: true

        - name: Install packages that will be removed by the role (regex targets)
          ansible.builtin.package:
            name: "{{ common_pkgs_apk.remove_regex_test }}"
            state: present
          become: true
          when: common_pkgs_apk.remove_regex_test is defined

    - name: FreeBSD preparation
      when: ansible_os_family == 'FreeBSD'
      block:
        - name: Install packages that will be removed by the role (direct)
          ansible.builtin.package:
            name: "{{ common_pkgs_pkgng.remove }}"
            state: present
          become: true
          environment:
            IGNORE_OSVERSION: "yes"

        - name: Install packages that will be removed by the role (regex targets)
          ansible.builtin.package:
            name: "{{ common_pkgs_pkgng.remove_regex_test }}"
            state: present
          become: true
          environment:
            IGNORE_OSVERSION: "yes"
          when: common_pkgs_pkgng.remove_regex_test is defined

    - name: Windows preparation
      when: ansible_os_family == 'Windows'
      block:
        - name: Install packages that will be removed by the role
          chocolatey.chocolatey.win_chocolatey:
            name: "{{ common_pkgs_chocolatey.remove }}"
            state: present
          become: true
          become_method: ansible.builtin.runas
          become_user: SYSTEM
