---
- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../vars/molecule.yml

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert that test packages are installed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages is defined
          - package in ansible_facts.packages
        fail_msg: "Package {{ package }} is NOT installed"
      loop: "{{ common_pkgs[ansible_facts['pkg_mgr']].install }}"
      loop_control:
        loop_var: package

    - name: Assert that test packages are removed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages is defined
          - package not in ansible_facts.packages
        fail_msg: "Package {{ package }} is STILL installed"
      loop: "{{ common_pkgs[ansible_facts['pkg_mgr']].remove }}"
      loop_control:
        loop_var: package

    - name: Assert that test regex packages are removed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages is defined
          - package not in ansible_facts.packages
        fail_msg: "Regex Package {{ package }} is STILL installed"
      loop: "{{ common_pkgs[ansible_facts['pkg_mgr']].remove_regex_test }}"
      loop_control:
        loop_var: package
